services:
  # Basic image for using TNG. Does NOT have unpacked files and initial configuration!
  tng:
    container_name: tng
    image: tng:latest
    ports:
      - ${TNG_PORT:-8888}:80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sL", "http://localhost/readme.html"]
      interval: 30s
      timeout: 10s
      retries: 3
    tty: true
    stdin_open: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - data:/var/www/html
      - php_conf:/usr/local/etc/php
    depends_on:
      tng_db:
        condition: service_healthy
      tng_init:
        condition: service_completed_successfully

  tng_init:
    # Perform TNG file unpacking and initialization
    image: tng:latest
    container_name: tng_init
    build:
      context: .
      dockerfile_inline: |
        # Dockerfile for TNG Family Tree Web app
        # - https://www.tngsitebuilding.com/
        # - Pre-requisites: install your download of tng12.1 in the file where this Dockerfile resides
        #
        # Ideas for this Dockerfile were inspired by
        #   https://github.com/sprintcube/docker-compose-lamp/blob/master/bin/webserver/Dockerfile
        
        FROM php:7-apache

        COPY ${TNG_ZIP_FILE:-tng*.zip} /var/www/html/
        COPY ./tng_init.sh /var/www/html
        COPY ./.env /var/www/html
        
        RUN docker-php-ext-install pdo_mysql
        RUN docker-php-ext-install mysqli
        RUN apt-get update -y && apt-get install -y unzip
        RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
    restart: no
    command: [ "/bin/bash", "/var/www/html/tng_init.sh" ]
    tty: true
    stdin_open: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - data:/var/www/html
      - php_conf:/usr/local/etc/php
    depends_on:
      tng_db:
        condition: service_healthy

  tng_db:
    image: mysql:latest
    container_name: tng_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${TNG_DB_PORT:-3306}:3306
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo"
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: 'phpmyadmin'
#    restart: unless-stopped
#    links:
#      - tng_db:db
#    env_file:
#      - .env
#    environment:
#      - PMA_HOST=tng_db
#      - PMA_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      #- PMA_ARBITRARY=1
#    ports:
#      - ${PMA_PORT:-8080}:80
#    depends_on:
#      - tng_db

volumes:
  db:
  data:
  php_conf:

